version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgresDev
      POSTGRES_PASSWORD: postgresDev
      POSTGRES_DB: fast_notes
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: